name: 🎮 PSVita Builds
on:
  workflow_call:

# Global Settings
env:
  GODOT_BASE_BRANCH: 3.x
  SCONSFLAGS: verbose=yes warnings=all werror=no debug_symbols=no
  VITASDK: /usr/local/vitasdk
  EUID: 1 makepkg

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-vita
  cancel-in-progress: true

jobs:
  vita-template:
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix:
        include:
          - vitagl: false
            suffix: ""
          - vitagl: true
            suffix: "-vitagl"
    name: "Template (target=release, tools=no)${{ matrix.suffix }}"

    steps:
      - uses: actions/checkout@v2

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: vita-template${{ matrix.suffix }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Setup VitaSDK
        run: |
          sudo apt-get install cmake libarchive-tools fakeroot zip -y
          git clone https://github.com/vitasdk/vdpm
          git clone https://github.com/isage/vita-packages-extra
          cd vdpm
          ./bootstrap-vitasdk.sh
          export PATH=$VITASDK/bin:$PATH
          export VDPM_NONINTERACTIVE=1
          vdpm openssl-1.1.1
          . "$VITASDK/bin/include/install-packages.sh"
          filtered_packages=()
          for p in "${PACKAGES[@]}"; do
            [[ "$p" == "openssl" ]] || filtered_packages+=("$p")
          done
          PACKAGES=("${filtered_packages[@]}")
          install_packages
          vdpm vita-rss-libdl
          cd ../vita-packages-extra/pvr_psp2
          vita-makepkg
          vdpm *-vita.pkg.tar.xz

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: "${{ env.SCONSFLAGS }} vitagl=${{ matrix.vitagl }}"
          platform: vita
          target: release
          tools: false

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: vita-template${{ matrix.suffix }}
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: vita-template${{ matrix.suffix }}
